name: Warning

"on":
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - extensions
    paths-ignore:
      - 'extensions/**.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'extensions/**.json'

jobs:
  wrong-file-warning:
    runs-on: ubuntu-latest

    steps:
      - name: Warning
        run: |
          echo You are probably adding me wrong file
          echo Extension entries goes into extensions directory and must be in json format
          echo Don't edit other files unless there's a special reason
          exit 1
